### ISSUE TITLE
Illager spawns in ocean biomes (0.6.0)

### ISSUE THREAD

**Issue by intemptesta** [pentantan/HunterIllager#11]
MC: 1.15.2
Forge: 31.1.48 server
Hunter Illagers: 0.6.0

Happened the same as this issue;
> https://github.com/pentantan/HunterIllager/issues/9

Furthermore, when strumbled upon those ocean hunters, chunks would stop generate and the server will freeze, without any error log.

Mod list and errors to help identify the problem;
https://gist.github.com/intemptesta/172b18dfd0431f8a87dac808be4584f3

**Comment by pentantan** [comment]
It's fixed on 0.7.0
