### ISSUE TITLE
Crash with version 0.7.1 for 1.15.2 with itemstack function

### ISSUE THREAD

**Issue by 3x1at1on** [pentantan/HunterIllager#12]
I know this is weird but there is no crash with version 0.7.0 and the crash happens with 0.7.1

Crash log does not mention your mod at all but definitely something to do with the code you added in 0.7.1 as the game loads just fine with 0.7.0

I suspect this has something to do with the code you added conflicting with mixin or dank storage for some weird reason (not an avid coder I must admit).
src/main/java/baguchan/hunterillager/item/BoomerangItem.java
`    @Override
    public Multimap<String, AttributeModifier> getAttributeModifiers(EquipmentSlotType slot, ItemStack stack) {
        return null;
    }
`

Crash log https://pastebin.com/MuGNdgYz
Full log https://pastebin.com/1YBpN9Ke

**Comment by bessiq** [comment]
Also just installed this mod for the first time today, and the game would crash during initial loading until I disabled Hunter Illager - version 0.7.1.

But seems like a neat mod, so going to downgrade to the previous version for now!

**Comment by pentantan** [comment]
ah sorry for mistake code
I upload HunterIllager-1.15.2-0.7.1-bugfix agein
so that version was fixed crash

**Comment by 3x1at1on** [comment]
That fixed the crash. Many thanks.
