### ISSUE TITLE
[1.16.1] Unknown Structure Starts returning NullPointerExceptions on chunk saves on the BYG WorldType(possibly other world types too).

### ISSUE THREAD

**Issue by CorgiTaco** [pentantan/HunterIllager#15]
Hello! I'd like to report an issue that seems to be related to your mod that was reported here: https://github.com/CorgiTaco/BYG/issues/15 .

See the first link on the issue I linked at line 4955.

In 1.16 structures are hardcoded to a list inside the class DimensionStructureSettings on line 21. Do you add the "hunterillager:hunterhouse" too this list? I believe this is the source of the issue(correct me if I'm wrong).

Have a good day :)

**Comment by pentantan** [comment]
yep, thats source issue
this error is fixed in 1.16.1-0.8.3
