### ISSUE TITLE
Camp spawn in water

### ISSUE THREAD

**Issue by KorDum** [pentantan/HunterIllager#3]
Small generation bug, see screenshots. Can you check water near for generation?
Version 1.14.4-0.1.0

![image](https://user-images.githubusercontent.com/1331559/62554220-68c7f800-b879-11e9-97c4-248919224677.png)

![image](https://user-images.githubusercontent.com/1331559/62554306-90b75b80-b879-11e9-915a-858d7e99b9fa.png)

**Comment by pentantan** [comment]
It fixed in 0.1.3 :)
