### ISSUE TITLE
Camp spawn in ground

### ISSUE THREAD

**Issue by KorDum** [pentantan/HunterIllager#4]
Small generation bug, see screenshots. Can you check air near for generation?
Version 1.14.4-0.1.0

![image](https://user-images.githubusercontent.com/1331559/62599445-e846dd00-b8f4-11e9-8851-1de1a6dd85cc.png)

![image](https://user-images.githubusercontent.com/1331559/62599619-60150780-b8f5-11e9-87cb-9d5c99cb08a4.png)

**Comment by KorDum** [comment]
Incorrect generation house too

![image](https://user-images.githubusercontent.com/1331559/62831208-2b21f100-bc24-11e9-8b39-9fb96eae51dd.png)

**Comment by pentantan** [comment]
fixed in 0.1.3 :)
