### ISSUE TITLE
Illager spawns in ocean biomes

### ISSUE THREAD

**Issue by dreckz** [pentantan/HunterIllager#9]
MC: 1.15.2
Forge: 31.1.25
Hunter Illagers: 0.5.0

I found hunter illagers spawning out in the middle of ocean biomes.  Is there a way to blacklist which biomes illagers spawn themselves in?

![image](https://user-images.githubusercontent.com/59788491/77224690-3207cf00-6b36-11ea-9dc8-6d774be0976c.png)
![image](https://user-images.githubusercontent.com/59788491/77224699-3d5afa80-6b36-11ea-8326-05a1d6a9af00.png)

**Comment by pentantan** [comment]
fixed in 0.6.0
If still spawn it, please tell me. :)
